# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-17 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiledatarule',
            options={'verbose_name': 'Profile Data Rule'},
        ),
    ]
