# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0008_devicerule'),
        ('personalise', '0003_personalisablesurvey_personalisablesurveyformfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmissionDataRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='field name')),
                ('expected_response', models.CharField(help_text='Multiple choice values must be separated with commas.', max_length=255, verbose_name='expected response')),
                ('operator', models.CharField(choices=[(b'eq', 'equals'), (b'in', 'contains')], default=b'in', max_length=3, verbose_name='operator')),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalise_surveysubmissiondatarule_related', related_query_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.Segment')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalise.PersonalisableSurvey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'Survey submission rule',
            },
        ),
    ]
