# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('wagtail_personalisation', '0008_devicerule'),
        ('personalise', '0004_surveysubmissiondatarule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembershipRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(help_text='User must be part of this group to activate the rule.', on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalise_groupmembershiprule_related', related_query_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.Segment')),
            ],
            options={
                'verbose_name': 'Group membership rule',
            },
        ),
    ]
