# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0008_devicerule'),
        ('personalise', '0005_groupmembershiprule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDataRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_content', models.TextField(verbose_name='expected content')),
                ('operator', models.CharField(choices=[(b'eq', 'equals'), (b'in', 'contains')], default=b'in', max_length=3, verbose_name='operator')),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalise_commentdatarule_related', related_query_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.Segment')),
            ],
            options={
                'verbose_name': 'comment data rule',
            },
        ),
    ]
