# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0008_devicerule'),
        ('personalise', '0006_commentdatarule'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalisablesurvey',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='Leave it empty to show this surveyto every user.', null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtail_personalisation.Segment'),
        ),
    ]
