# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-14 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0007_personalisablesurvey_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdatarule',
            name='expected_content',
            field=models.TextField(help_text="Content that we want to match in user's comment data.", verbose_name='expected content'),
        ),
        migrations.AlterField(
            model_name='commentdatarule',
            name='operator',
            field=models.CharField(choices=[(b'eq', 'equals'), (b'in', 'contains')], default=b'in', help_text='"Equals" operator will match only the exact content. "Contains" operator matches a part of a comment.', max_length=3, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='profiledatarule',
            name='operator',
            field=models.CharField(choices=[(b'lt', 'Less than'), (b'lte', 'Less than or equal'), (b'gt', 'Greater than'), (b'gte', 'Greater than or equal'), (b'eq', 'Equal'), (b'neq', 'Not equal'), (b'ol', 'Older than'), (b'ole', 'Older than or equal'), (b'yg', 'Younger than'), (b'yge', 'Younger than or equal'), (b'eqa', 'Of age'), (b'reg', 'Regex')], default=b'eq', help_text='Age operators work only on dates, please input the age you want to compare in "value". When using greater/less than on text field, it would compare it by alphabetical order, where dates are compared to the specified date by chronological order.', max_length=3),
        ),
        migrations.AlterField(
            model_name='profiledatarule',
            name='value',
            field=models.CharField(help_text='If the selected field is a text field you can just input text. In case of dates, please use format "YYYY-MM-DD" and "YYYY-MM-DD HH:MM" for date-times. For regex please refer to the usage docs. If it is a choice field, please input anything, save and the error message displayed below this field should guide you with possible values.', max_length=255),
        ),
        migrations.AlterField(
            model_name='surveysubmissiondatarule',
            name='expected_response',
            field=models.CharField(help_text='When comparing text values, please input text. Comparison on text is always case-insensitive. Multiple choice values must be separated with commas.', max_length=255, verbose_name='expected response'),
        ),
        migrations.AlterField(
            model_name='surveysubmissiondatarule',
            name='field_name',
            field=models.CharField(help_text="Field's label in a lower-case format with spaces replaced by dashes. For possible choices please input any text and save, so it will be displayed in the error messages below the field.", max_length=255, verbose_name='field name'),
        ),
        migrations.AlterField(
            model_name='surveysubmissiondatarule',
            name='operator',
            field=models.CharField(choices=[(b'eq', 'equals'), (b'in', 'contains')], default=b'in', help_text='When using the "contains" operator, "expected response" can contain a small part of user\'s response and it will be matched. "Exact" would match responses that are exactly the same as the "expected response".', max_length=3, verbose_name='operator'),
        ),
    ]
