# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0008_improve_personalise_rules_helptexts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalisablesurvey',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='Leave it empty to show this surveyto every user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtail_personalisation.Segment'),
        ),
    ]
