# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-15 14:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0009_personalisable_survey_segment_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalisablesurveyformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalisable_survey_form_fields', to='personalise.PersonalisableSurvey'),
        ),
    ]
