# Generated by Django 2.2.1 on 2019-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190503_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='videospage',
            name='videourl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
