# Generated by Django 2.2.1 on 2019-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarticle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videospage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
