# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0004_auto_20160621_1130'),
        ('gem', '0007_move_pages_to_index_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemReportComment',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gem_comment', serialize=False, to='commenting.MoloComment')),
                ('reported_reason', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
