# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commenting', '0004_auto_20160628_1557'),
        ('gem', '0008_create_importers_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_reason', models.CharField(max_length=128)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gem_comment', to='commenting.MoloComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
