# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0009_gemcommentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='banned_names_with_offensive_language',
            field=models.TextField(blank=True, help_text=b'Banned names with offensive language, separated by a line a break. Use only lowercase letters for keywords.', null=True, verbose_name=b'Preventing Display Names With Offensive Language'),
        ),
    ]
