# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0011_auto_20161019_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='partner_credit_description',
            field=models.TextField(blank=True, help_text=b'The text that will be shown for the partner credit  e.g. "Translated by Sajan"', null=True),
        ),
        migrations.AddField(
            model_name='gemsettings',
            name='partner_credit_link',
            field=models.TextField(blank=True, help_text=b' The link that the partner credit will redirect to e.g. https://www.google.co.za/', null=True),
        ),
        migrations.AddField(
            model_name='gemsettings',
            name='show_partner_credit',
            field=models.BooleanField(default=False, help_text=b'When true, this will show the partner credit on the homepage.'),
        ),
    ]
