# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0012_partner_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='moderator_name',
            field=models.TextField(blank=True, help_text=b'Moderator name', null=True, verbose_name=b'Moderator Name'),
        ),
    ]
