# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0012_partner_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='moderator_name',
            field=models.TextField(blank=True, help_text=b'This is the name that will appear on the front end when a moderator responds to a user', null=True, verbose_name=b'Moderator Name'),
        ),
    ]
