# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-23 14:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0013_gemsettings_moderator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemuserprofile',
            name='migrated_username',
            field=models.CharField(blank=True, error_messages={b'unique': 'A user with that username already exists.'}, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(b'^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='migrated_username'),
        ),
    ]
