# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0016_remove_unique_constraint_on_migrated_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='show_join_banner',
            field=models.BooleanField(default=False, help_text=b'When true, this will show the join banner on the homepage.'),
        ),
    ]
