# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0017_show_join_banner_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='bbm_ga_account',
            field=models.TextField(blank=True, help_text=b'Additional Google Analytics account', null=True),
        ),
        migrations.AddField(
            model_name='gemsettings',
            name='bbm_ga_account_subdomain',
            field=models.TextField(default=b'bbm', help_text=b'Subdomain prefix to seperate traffics data for Google Analytics. Defaults to "bbm"'),
        ),
        migrations.AlterField(
            model_name='gemuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'f', 'female'), (b'-', "don't want to answer"), (b'm', 'male')], max_length=1, null=True),
        ),
    ]
