# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-11 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0018_add_extra_ga_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='bbm_app_id',
            field=models.TextField(blank=True, help_text=b'Application ID for BBM', null=True),
        ),
    ]
