# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0018_add_extra_ga_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemuserprofile',
            name='registration_token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='gemuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'f', 'female'), (b'm', 'male'), (b'-', "don't want to answer")], max_length=1, null=True),
        ),
    ]
