# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0018_add_extra_ga_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemsettings',
            name='bbm_ga_account',
        ),
        migrations.AddField(
            model_name='gemsettings',
            name='bbm_ga_tracking_code',
            field=models.TextField(blank=True, help_text=b'Tracking code for additional Google Analytics account to divert traffic that matches a specific subdomain.', null=True),
        ),
    ]
