# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0019_change_setting_bbm_ga_account_to_bbm_ga_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'f', 'female'), (b'm', 'male'), (b'-', "don't want to answer")], max_length=1, null=True),
        ),
    ]
