# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0012_remove_personalisablepagemetadata_is_segmented'),
        ('gem', '0020_profiledatarule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCountRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[(b'gt', 'greater than'), (b'lt', 'less than'), (b'eq', 'equals')], default=b'gt', max_length=3, verbose_name='operator')),
                ('count', models.PositiveSmallIntegerField()),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gem_commentcountrule_related', related_query_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.Segment')),
            ],
            options={
                'verbose_name': 'Comment count rule',
            },
        ),
    ]
