# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-26 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0023_move_migrated_user_name_to_molo_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemuserprofile',
            name='migrated_username',
        ),
    ]
