# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0027_set_site_settings_correctly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemsettings',
            name='bbm_ga_tracking_code',
            field=models.TextField(blank=True, help_text='Google Analytics account ID (UA-XXXXXXXX-X) to use when somebody accesses the BBM version of the site.', null=True),
        ),
    ]
