# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 12:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('gem', '0027_set_site_settings_correctly'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oidc_rp_client_id', models.CharField(max_length=255)),
                ('oidc_rp_client_secret', models.CharField(max_length=255)),
                ('oidc_rp_scopes', models.CharField(blank=True, default=b'openid profile email address phone site roles', max_length=255)),
                ('extra_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('wagtail_redirect_url', models.URLField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
        ),
    ]
