# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 14:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0028_oidc_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcsettings',
            name='extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
