# flake8: noqa: E128
# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 12:20
from __future__ import unicode_literals

from django.db import migrations
from django.core.management.sql import emit_post_migrate_signal


def add_view_yourwords_entry_to_groups(apps, schema_editor):
   pass


class Migration(migrations.Migration):
    dependencies = [
        ('gem', '0030_create_groups_and_permissions'),
        ('core', '0002_add_can_view_response_reaction_question_permission'),
    ]

    operations = [
        migrations.RunPython(add_view_yourwords_entry_to_groups),
    ]
