# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0032_remove_gem_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcountrule',
            name='operator',
            field=models.CharField(choices=[('gt', 'greater than'), ('lt', 'less than'), ('eq', 'equals')], default='gt', max_length=3, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='banned_keywords_and_patterns',
            field=models.TextField(blank=True, help_text='Banned keywords and patterns for comments, separated by a line a break. Use only lowercase letters for keywords.', null=True, verbose_name='Banned Keywords and Patterns'),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='banned_names_with_offensive_language',
            field=models.TextField(blank=True, help_text='Banned names with offensive language, separated by a line a break. Use only lowercase letters for keywords.', null=True, verbose_name='Banned Names With Offensive Language'),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='bbm_ga_account_subdomain',
            field=models.TextField(default='bbm', help_text='Subdomain prefix to seperate traffics data for Google Analytics. Defaults to "bbm"'),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='bbm_ga_tracking_code',
            field=models.TextField(blank=True, help_text='Tracking code for additional Google Analytics account to divert traffic that matches a specific subdomain.', null=True),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='moderator_name',
            field=models.TextField(blank=True, help_text='This is the name that will appear on the front end when a moderator responds to a user', null=True, verbose_name='Moderator Name'),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='partner_credit_description',
            field=models.TextField(blank=True, help_text='The text that will be shown for the partner credit  e.g. "Translated by Sajan"', null=True),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='partner_credit_link',
            field=models.TextField(blank=True, help_text=' The link that the partner credit will redirect to e.g. https://www.google.co.za/', null=True),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='show_join_banner',
            field=models.BooleanField(default=False, help_text='When true, this will show the join banner on the homepage.'),
        ),
        migrations.AlterField(
            model_name='gemsettings',
            name='show_partner_credit',
            field=models.BooleanField(default=False, help_text='When true, this will show the partner credit on the homepage.'),
        ),
        migrations.AlterField(
            model_name='oidcsettings',
            name='oidc_rp_scopes',
            field=models.CharField(blank=True, default='openid profile email address phone site roles', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiledatarule',
            name='operator',
            field=models.CharField(choices=[('lt', 'Less than'), ('lte', 'Less than or equal'), ('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('eq', 'Equal'), ('neq', 'Not equal'), ('ol', 'Older than'), ('ole', 'Older than or equal'), ('yg', 'Younger than'), ('yge', 'Younger than or equal'), ('eqa', 'Of age'), ('reg', 'Regex')], default='eq', help_text='Age operators work only on dates, please input the age you want to compare in "value". When using greater/less than on text field, it would compare it by alphabetical order, where dates are compared to the specified date by chronological order.', max_length=3),
        ),
    ]
