# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0033_auto_20190122_0731'),
        ('gem', '0033_auto_20190123_1658'),
    ]

    operations = [
    ]
