# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0034_merge_20190124_1052'),
        ('gem', '0033_auto_20190125_1150'),
    ]

    operations = [
    ]
