# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0035_merge_20190125_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='fb_enable_chat_bot',
            field=models.BooleanField(default=False, help_text='Activate chat-bot for facebook messenger.'),
        ),
    ]
