# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0037_remove_content_editor_survey_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_choice_text', models.CharField(max_length=200)),
                ('questionnaire_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ThaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='questionnairechoice',
            name='tha_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gem.ThaQuestion'),
        ),
    ]
