# Generated by Django 2.2.7 on 2019-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0038_create_permissions_for_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemsettings',
            name='enable_comment_threads',
            field=models.BooleanField(default=False),
        ),
    ]
