# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0038_auto_20190913_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThaQuestion',
            new_name='Questionnaire',
        ),
        migrations.RenameField(
            model_name='questionnairechoice',
            old_name='tha_question',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questionnairechoice',
            old_name='questionnaire_votes',
            new_name='questionnaire_choice_votes',
        ),
    ]
