# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-13 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0039_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_choice_text', models.CharField(max_length=200)),
                ('questionnaire_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='ThaQuestion',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='thaquestion',
            old_name='question_text',
            new_name='questionnaire_text',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='questionnairechoice',
            name='tha_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gem.ThaQuestion'),
        ),
    ]
