# Generated by Django 2.2.10 on 2020-02-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('gem', '0042_add_user_to_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
    ]
