# Generated by Django 3.1.5 on 2021-01-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0044_remove_deprecated_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemsettings',
            name='bbm_ga_account_subdomain',
        ),
        migrations.RemoveField(
            model_name='gemsettings',
            name='bbm_ga_tracking_code',
        ),
        migrations.RemoveField(
            model_name='oidcsettings',
            name='oidc_rp_client_id',
        ),
        migrations.RemoveField(
            model_name='oidcsettings',
            name='oidc_rp_client_secret',
        ),
        migrations.RemoveField(
            model_name='oidcsettings',
            name='oidc_rp_scopes',
        ),
        migrations.RemoveField(
            model_name='oidcsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='oidcsettings',
            name='wagtail_redirect_url',
        ),
    ]
