from gem.admin import GemFrontendUsersModelAdmin, GemCommentModelAdmin
from wagtail.contrib.modeladmin.options import modeladmin_register

modeladmin_register(GemFrontendUsersModelAdmin)
modeladmin_register(GemCommentModelAdmin)
