name: Publish Docker Image

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Get molo version
        id: get_molo_version
        run: |
            molo_version="$(sed -nE 's/^molo\.core==(.*)$/\1/p' requirements.txt)"
            echo "::set-output name=MOLO_VERSION::${molo_version}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          push: true
          repository: praekeltfoundation/molo-gem
          tag_with_ref: true
          tag_with_sha: true
          tags: "latest"
          username: praekeltorgdeploy
          password: ${{ secrets.DOCKER_HUB_PASS }}
          build_args: |
            ${{ steps.get_molo_version.outputs.MOLO_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
